- name: Install GCC
  apt:
    name: 'gcc'

- name: Install Redis
  shell: make && make install
  args:
    chdir: /opt/redis-{{redis_version}}
  when: redis_version == "{{ redis_version_meta[6.0].version }}" 
