- name: Install GCC for Redis6.0, refer to https://github.com/redis/redis/issues/7509
  shell: |
      sudo yum -y install centos-release-scl devtoolset-7 llvm-toolset-7
      scl enable devtoolset-7 llvm-toolset-7 bash
  when: redis_version == "6.0"

- set_fact: redis_version="{{ redis_version_meta[redis_version].version }}"

- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Download Redis Source Code from {{redis_download_url}}
  unarchive:
    src: "{{redis_download_url}}/redis-{{redis_version}}.tar.gz"
    dest: /opt/
    remote_src: yes

- name: Install Redis
  shell: make && make install
  args:
    chdir: /opt/redis-{{redis_version}}

- name: Create Redis dir
  file: 
    path: "{{item}}"
    state: directory
  with_items:
    - /etc/redis
    - /data/redis
    - /var/log/redis

- name: Copy Redis config
  shell: cp /opt/redis-{{redis_version}}/redis.conf /etc/redis/redis_server_0.conf

- name: Set Redis default config
  lineinfile:
    dest: /etc/redis/redis_server_0.conf
    regexp: '^{{ item.name }}  *'
    firstmatch: yes
    line: "{{ item.name }}   {{item.value}}"
  with_items: "{{ redis_configuration_default }}"
  when: redis_configuration_default is defined and redis_configuration_default != none

- name: Set Redis extra config
  lineinfile:
    dest: /etc/redis/redis_server_0.conf
    regexp: '^{{ item.name }}  *'
    firstmatch: yes
    line: "{{ item.name }}   {{item.value}}"
  with_items: "{{ redis_configuration_extra }}"
  when: redis_configuration_extra is defined and redis_configuration_extra != none

- name: Fix redis server status warning
  shell: |
    echo "net.core.somaxconn= 1024" >>/etc/sysctl.conf
    echo "vm.overcommit_memory = 1" >>/etc/sysctl.conf
    sysctl -p
    echo never > /sys/kernel/mm/transparent_hugepage/enabled
    echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" |tee -a rc.local

- name: Config Redis Service
  copy: 
    src: redis.service
    dest: /lib/systemd/system/

- name: Start Redis
  service:
    name: redis.service
    state: started
    enabled: yes

- name: Create a Redis symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /etc/redis/redis_server_0.conf,dest: /data/redis/redis_server_0.conf}
    - {src: /etc/redis/redis_server_0.conf,dest: /etc/redis_server_0.conf}
    - {src: /etc/redis/redis_server_0.conf,dest: /data/config/redis_server_0.conf}
    - {src: /var/log/redis,dest: /data/redis/log}
    - {src: /var/log/redis,dest: /data/logs/redis}
    - {src: /data/redis,dest: /var/lib/redis}

- name: Copy Redis source file
  shell: cp -R /opt/redis-{{redis_version}}/* /data/redis/

- name: Check redis Version
  shell: sudo sh -c "/usr/local/bin/redis-server -v 1>> /data/logs/install_version.txt"

- include_tasks: "RedisInsight.yml"
  when: redis_install_redisinsight