- set_fact: redis_version="{{ redis_version_meta[redis_version].version }}"

- name: Install GCC
  yum:
    name: 'gcc'
  when: ansible_os_family == 'RedHat'

- name: Install GCC
  apt:
    name: 'gcc'
  when: ansible_os_family == 'Debian'

- name: Download Redis Source Code from {{redis_download_url}}
  unarchive:
    src: "{{redis_download_url}}/redis-{{redis_version}}.tar.gz"
    dest: /opt/
    remote_src: yes

- name: Install redis
  shell: make && make install
  args:
    chdir: /opt/redis-{{redis_version}}

- name: Delete redis source code
  file:
    path: /opt/redis-{{redis_version}}
    state: absent

- name: create redis dir
  file: 
    path: "{{item}}"
    state: directory
  with_items:
    - /etc/redis
    - /data/redis
    - /var/log/redis

- name: Copy redis config
  copy:
    src: redis.conf
    dest: /etc/redis

- name: config Redis Service
  copy: 
    src: redis.service
    dest: /lib/systemd/system/

- name: Start Redis
  service:
    name: redis.service
    state: started
    enabled: yes

# create soft link for old documentation, ln -sb 
- name: Create a redis symbolic link
  shell: |
    ln -sb /etc/redis /data/config/redis
    ln -sb /etc/redis/redis.conf /etc/redis.conf
    ln -sb /data/redis /var/lib/redis

- name: Check redis Version
  shell: sudo sh -c "/usr/local/bin/redis-server -v 1>> /data/logs/install_version.txt"

# Install RedisInsight
- include_tasks: "RedisInsight.yml"
  when: redis_install_redisinsight
