- name: Install GCC
  yum:
    name: gcc

- block:
  - name: Install GCC for Redis6.0, refer to https://github.com/redis/redis/issues/7509
    yum:
      name: [centos-release-scl,devtoolset-7,llvm-toolset-7]

  - name: make 
    shell: scl enable devtoolset-7 llvm-toolset-7 -- make
    args:
      chdir: /opt/redis-{{redis_version}}

  - name: make install
    shell: make install
    args:
      chdir: /opt/redis-{{redis_version}}
  when: redis_version == "{{ redis_version_meta["6.0"].version }}" and ansible_distribution == 'CentOS'
