# docs: https://docs.redislabs.com/latest/index.html

- name: Create Redis insight Dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/redisinsight
    - /var/log/redisinsight

- name: Download Redis insight
  get_url:
    url: "{{ redis_redisinsight_url }}"
    dest: /usr/local/redisinsight/redisinsight
    mode: '0750'

- name: Config Service
  copy:
    src: redisinsight.service 
    dest: /usr/lib/systemd/system/redisinsight.service

- name: Config redisinsight
  template:
    src: redisinsight-config.jinja2
    dest: /etc/sysconfig/redisinsight-config

- name: Start redisinsight
  service:
    name: redisinsight
    state: started
    enabled: yes
 
 - name: Set soft link for RedisInsight
   shell: |
     ln -sb /usr/local/redisinsight /data/redisinsight
     ln -sb /var/log/redisinsight /data/logs/redisinsight
     ln -sb /etc/sysconfig/redisinsight-config /data/config
